app/models.py
#!flask/bin/python
# -*- coding: utf-8 -*-

from werkzeug.security import generate_password_hash, check_password_hash
from app import db
from . import login_manager


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True, index=True)
    nickname = db.Column(db.String(100), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        try:
            return unicode(self.id)  # python 2
        except NameError:
            return str(self.id)  # python 3


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    # name = db.Column(db.int)


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), index=True)
    body = db.Column(db.Text)
    markdown_resource = db.Column(db.Text)
    create_time = db.Column(db.DateTime)
    edit_time = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    is_published = db.Column(db.Boolean)
    comments = db.relationship('Comment', backref='post', lazy='dynamic')


class Comment(db.Model):
    __tablename__ = 'commnents'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    create_time = db.Column(db.DateTime)
    email = db.Column(db.String(100))
    nickname = db.Column(db.String(100))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))



@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

app/admin/forms.py
#!flask/bin/python
# -*- coding: utf-8 -*-from flask.ext.wtf import Form

from flask.ext.wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length


class UserForm(Form):
    email = StringField(u'邮箱', validators=[DataRequired()])
    nickname = StringField(u'昵称', validators=[DataRequired()])
    password = PasswordField(u'密码', validators=[DataRequired()])

app/main/forms.py
#!flask/bin/python
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms import StringField, TextAreaField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Length


class PostForm(Form):
    title = StringField(u'标题', validators=[DataRequired()])
    body = StringField()
    markdown_resource = StringField()


class CommentForm(Form):
    nickname = StringField(u'昵称')
    email = StringField(u'邮箱')
    body = StringField(u'评论', validators=[DataRequired()])

app/__init__.py
#!flask/bin/python
# -*- coding: utf-8 -*-

from flask import Flask

from config import config
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager


db = SQLAlchemy()
login_manager = LoginManager()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'
    login_manager.login_message = u'该页面需要登录后才能访问'
    return app

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from .import views

app/admin/views.py
#!flask/bin/python
# -*- coding: utf-8 -*-

from flask import render_template
from flask.ext.login import login_required,login_user,logout_user,current_user
from .import admin, forms
from ..models import User


@admin.route('/')
@admin.route('/index')
@login_required
def index():
    return render_template("admin.html")


@admin.route('/user/create', methods=['GET', 'POST'])
def create_user():
    form = forms.UserForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, nickname=form.nickname.data)
        user.password = form.password.data

        db.session.add(user)
        db.session.commit()
    return render_template("create_user.html",form=form)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
#!flask/bin/python
# -*- coding: utf-8 -*-
import datetime
from flask import render_template, url_for, redirect, g, flash, request

from .import main
from app.main import forms

from flask.ext.login import login_required, login_user, logout_user, current_user
from app import login_manager, db
from ..models import Post, Comment


@main.route('/')
@main.route('/index')
def index():
    posts = Post.query.filter_by(is_published=True).order_by('edit_time').paginate(1, 4, False).items
    return render_template("index.html", posts=posts)


@main.route('/post/list', methods=['GET'])
@main.route('/post/list/<int:page>', methods=['GET'])
@login_required
def post_list(page=1):
    pagination = Post.query.order_by('edit_time').paginate(page, 10, False)
    return render_template("post_list.html", pagination=pagination, route_='.post_list')


@main.route('/post/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = forms.PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    markdown_resource=request.form["editormd-markdown-doc"],
                    body=request.form["editormd-html-code"],
                    user_id=int(current_user.id),
                    create_time=datetime.datetime.now(),
                    edit_time=datetime.datetime.now())
        db.session.add(post)
        db.session.commit()
        flash(u"添加成功！")
        return redirect(url_for('.post_list'))
    return render_template("create_post.html", form=form)


@main.route('/post/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    form = forms.PostForm()
    post = Post.query.get(int(id))
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = request.form["editormd-html-code"]
        post.markdown_resource = request.form["editormd-markdown-doc"],
        post.edit_time = datetime.datetime.now()
        db.session.add(post)
        db.session.commit()
        flash(u"修改成功！")
        return redirect(url_for('.post_list'))
    form.title.data = post.title
    form.body.data = post.body
    form.markdown_resource.data = post.markdown_resource
    return render_template("create_post.html", form=form)


@main.route('/post/delete/<id>', methods=['GET'])
def delete_post(id):
    post = Post.query.get(int(id))
    db.session.delete(post)
    db.session.commit()
    flash(u"删除成功！")
    return redirect(url_for('.post_list'))


@main.route('/post/publish/<id>', methods=['GET'])
def publish_post(id):
    post = Post.query.get(int(id))
    post.is_published = True
    db.session.commit()
    flash(u"发布成功！")
    return redirect(url_for('.post_list'))


@main.route('/post/notpublish/<id>', methods=['GET'])
def not_publish_post(id):
    post = Post.query.get(int(id))
    post.is_published = False
    db.session.commit()
    flash(u"取消发布成功！")
    return redirect(url_for('.post_list'))


@main.route('/p/')
@main.route('/p/index')
@main.route('/p/?<int:page>', methods=['GET'])
@main.route('/p/index/?<int:page>', methods=['GET'])
def post_index(page=1):
    pagination = Post.query.filter_by(is_published=True).order_by('edit_time').paginate(page, 10, False)
    return render_template("post_index.html", pagination=pagination, route_='main.post_index')


@main.route('/p/<id>')
def post_details(id):
    post = Post.query.get(int(id))
    form = forms.CommentForm()

    return render_template("post.html", post=post, form=form)


@main.route('/comment/<post_id>', methods=['POST'])
def comment(post_id):
    form = forms.CommentForm()
    if form.validate_on_submit():
        comment = Comment(nickname=form.nickname.data,
                          email=form.email.data,
                          create_time=datetime.datetime.now(),
                          body=form.body.data,
                          post_id=post_id)
        db.session.add(comment)
        db.session.commit()
        flash(u"评论成功！")
        return redirect(url_for('main.post_details',id=1))

app/templates/_admin.html
{% extends "_base.html" %}
{% block body %}
<div class="row">
    <div class="col-lg-12">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
    </div>
</div>
{% endblock %}

app/templates/_base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Leeway's Blog</title>
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/blog.css') }}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]>
    <script src="{{ url_for('static', filename='js/ie8-responsive-file-warning.js') }}"></script><![endif]-->
    <script src="{{ url_for('static', filename='js/ie-emulation-modes-warning.js') }}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head %}
    {% endblock %}
</head>

<body>
{% set navigation_bar = [
('main.index','index','首页',false),
('main.post_index','post_index','全部文章',false),
('auth.logout','logout','退出',true)
] %}

<div class="navbar navbar-default">
    <div class="container blog">
        <div class="navbar-header">
            <a href="../" class="navbar-brand">Leeway's Blog</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav">
                {% for view_name,id,caption,is_need_login in navigation_bar %}
                    {% if not is_need_login or current_user.is_authenticated() %}
                        <li>
                            <a class="nav-item" href="{{ url_for(view_name) }}"> {{ caption|e }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
            <!-- <ul class="nav navbar-nav navbar-right">
                 <li><a href="http://builtwithbootstrap.com/" target="_blank">Built With Bootstrap</a></li>
                 <li><a href="https://wrapbootstrap.com/?ref=bsw" target="_blank">WrapBootstrap</a></li>
             </ul>-->
        </div>
    </div>
</div>
<div class="container blog">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% block body %}
    {% endblock %}
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ url_for('static', filename='js/jquery-1.11.2.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{{ url_for('static', filename='js/ie10-viewport-bug-workaround.js') }}"></script>
<script type="text/javascript">

</script>
{% block js %}
{% endblock %}
</body>
</html>

app/templates/about.html
{% extends "_base.html" %}
{% set active_page = 'about' %}
{% block body %}
    <h2>
        关于我
    </h2>
    <p>
        很懒
    </p>
{% endblock%}

app/templates/admin.html
{% extends "_base.html" %}
{% set active_page = 'admin' %}

{% block body %}
    <a class="btn btn-primary" href="{{ url_for('main.post_list') }}">文章管理</a>
{% endblock %}

app/templates/create_post.html
{% extends "_base.html" %}
{% set active_page = 'admin' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='editor_md/css/editormd.min.css') }}"/>
{% endblock %}

{% block body %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class_="form-control") }}
    </div>
    <div class="form-group">
        <label>内容</label>
        <div id="editormd" class="form-control">
            {% if form.markdown_resource.data != None %}
               <textarea style="display:none;">{{ form.markdown_resource.data }}</textarea>
            {% endif %}
        </div>
        <input type="submit" class="btn btn-primary" value="保存"/>
</form>
{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='editor_md/editormd.min.js') }}"></script>
<script type="text/javascript">
    $(function() {
        var editor = editormd("editormd", {
        	width: "100%",
        	height: "640px",
            path : "{{ url_for('static', filename='editor_md/lib/') }}", // codemirror, marked等依赖的库的路径
            saveHTMLToTextarea: true
        });
    });

</script>
{% endblock %}

app/templates/create_user.html
{% extends "base.html" %}
{% set active_page = 'admin' %}

{% block body %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div>
        {{ form.email.label }}{{ form.email }}
    </div>
    <div> {{ form.nickname.label }}{{ form.nickname }}</div>
    <div> {{ form.password.label }}{{ form.password }}
    </div>
    <input type="submit" value="添加"/>
</form>
{% endblock %}

app/templates/index.html
{% extends "_base.html" %}
{% block body %}

<div class="page-header" id="banner">
    <div class="row">
        <div class="col-lg-12">
            <h1>Leeway's Blog</h1>
            <p class="lead">厚积薄发</p>
        </div>
    </div>
</div>

{% for post in posts %}
<div class="blog-post">
    <h2 class="blog-post-title"><a href="{{ url_for('main.post_details', id=post.id) }}" target="_blank">{{ post.title }}</a>
    </h2>

    <p class="blog-post-meta">{{ post.edit_time }}</p>
    {{ post.body|safe }}
</div>
{% endfor %}
<nav>
    <ul class="pager">
        <li><a href="{{ url_for('main.post_index') }}">全部文章</a></li>
    </ul>
</nav>
{% endblock %}

app/templates/pagination.html
<nav>
    <ul class="pagination">
        <li><a href="{{ url_for(route_) }}">首页</a></li>
        <li class="{{ '' if pagination.has_prev else 'disabled' }}">
            <a href="{{ url_for(route_, page=pagination.page-1) }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% if pagination.pages>3 %}
        {% set page_count = 3 %}
        {% else %}
        {% set page_count = pagination.pages %}
        {% endif %}
        {% for i in range(1, page_count + 1) %}
        {% if i == pagination.page %}
        <li class="active">
        {% else %}
        <li>
        {% endif %}
            <a href="{{ url_for(route_,page=i) }}">{{ i }}</a></li>
        {% endfor %}
        {% if pagination.pages>3 %}
        <li><span>...</span></li>
        <li>
            <a href="{{ url_for(route_,page=pagination.pages) }}">{{ pagination.pages }}</a></li>
        </li>
        {% endif %}
        <li class="{{ '' if pagination.has_next else 'disabled' }}">
            <a href="{{ url_for(route_, page=pagination.page+1) }}" aria-label="Next" aria-disabled="{{ pagination.has_next}}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        <li><a href="{{ url_for(route_, page=pagination.pages) }}">尾页</a></li>
    </ul>
</nav>

app/templates/post.html
{% extends "_base.html" %}
{% block body %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="post-title">{{ post.title }}</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="post-content">
            {{ post.body|safe }}
        </div>
    </div>
</div>
<!-- 评论的样式还没时间做
<div class="row">
    <div class="col-lg-12">
        <ul>
            <li>
                {% for comment in post.comments %}
                <div>
                    {{ comment.nickname }}
                </div>
                <div>
                    {{ comment.body }}
                </div>
                {% endfor %}
            </li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <form action="{{ url_for('main.comment',post_id=post.id)}}" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.nickname.label}} {{ form.nickname(class_="form-control") }}
            </div>
            <div class="form-group">
                {{ form.email.label}} {{ form.email(class_="form-control") }}
            </div>
            <div class="form-group">
                {{ form.body.label}} {{ form.body(class_="form-control") }}
            </div>
            <input type="submit" class="btn btn-primary" value="保存"/>
        </form>
    </div>
</div>
{% endblock%}
-->

app/templates/post_index.html
{% extends "_base.html" %}

{% block body %}

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-title">全部文章</h1>
        </div>
    </div>
<div class="row">
    <div class="col-lg-12">
        <ul class="post-list">
            {% for post in pagination.items %}
            <li>
                <a href="{{ url_for('main.post_details',id=post.id) }}" target="_blank">{{ post.title }}</a>
                <span>{{ post.create_time.date() }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        {% include "pagination.html" %}
    </div>
</div>
{% endblock%}

app/templates/post_list.html
{% extends "_base.html" %}
{% set active_page = 'admin' %}

{% block head %}
{% endblock%}
{% block body %}

<a class="btn btn-primary" href="{{ url_for('main.create_post') }}">新文章</a>
<hr>
<table class="table table-bordered">
    <tr>
        <th>
            标题
        </th>
        <th>
            状态
        </th>
        <th>
            操作
        </th>
    </tr>
    {% for post in pagination.items %}
    <tr>
        <td style="width:60%">
            <a href="{{ url_for('main.post_details',id=post.id) }}" target="_blank" style="display:block;margin-top:6px;">{{
                post.title }}</a>
        </td>
        <td>
            {% if not post.is_published %}
                未发布
            {% else %}
                已发布
            {% endif %}
        </td>
        <td>
            <a href="{{ url_for('main.edit_post', id=post.id) }}" class="btn btn-info">编辑</a>

            <a href="{{ url_for('main.delete_post', id=post.id)}}" class="btn btn-danger"
               onclick="javascript:confirm('确定删除该文章？')">删除</a>
            {% if not post.is_published %}
                <a href="{{ url_for('main.publish_post', id=post.id) }}" class="btn btn-info">发布</a>
            {% else %}
                <a href="{{ url_for('main.not_publish_post', id=post.id) }}" class="btn btn-info">取消发布</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% include "pagination.html" %}
<script>
</script>
{% endblock %}